version: "3"

services:
  python:
    build: .
    container_name: pmg-python
    ports:
      - 80:80
    volumes:
      - ./logs/gunicorn.log:${LOGS_PATH}
    environment:
      PORT: ${PORT}
      LOGS_PATH: ${LOGS_PATH}
      API_ENDPOINT: ${API_ENDPOINT}

  promtail:
    image: grafana/promtail
    container_name: pmg-promtail
    ports:
      - 9080:9080
    volumes:
      - ./logs:/var/log
      - ./monitoring/promtail.yaml:/etc/promtail/local-config.yaml
    environment:
      LOKI_IP: ${LOKI_IP}
    command: -config.expand-env=true -config.file=/etc/promtail/local-config.yaml
