version: "3"

services:
  loki:
    image: grafana/loki
    container_name: pmg-loki
    ports:
      - 3100:3100
    volumes:
      - ./monitoring/loki.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana
    container_name: pmg-grafana
    ports:
      - 3000:3000
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
    volumes:
      - ./grafana-data/grafana:/var/lib/grafana
    depends_on:
      - loki
